services:
  horametre:
    image: ghcr.io/aerya/horametre:latest
    container_name: horametre
    restart: always
    ports:
      - "8080:3000"
    environment:
      - AUTH_PASSWORD=${AUTH_PASSWORD:-horametre}
    volumes:
      - ./data:/app/data
